// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20240806171649_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Kompanija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrojDanaZaIsporuku")
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProsecnaZarada")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Kompanije");
                });

            modelBuilder.Entity("WebTemplate.Models.Roba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CenaDo")
                        .HasColumnType("int");

                    b.Property<int>("CenaOd")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIsporuke")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPrijema")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tezina")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloID")
                        .HasColumnType("int");

                    b.Property<int>("Zapremina")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VoziloID");

                    b.ToTable("Roba");
                });

            modelBuilder.Entity("WebTemplate.Models.Vozilo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIsporuke")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPrijema")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KompanijinoVoziloID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SlikaPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tezina")
                        .HasColumnType("int");

                    b.Property<int>("Zapremina")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KompanijinoVoziloID");

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("WebTemplate.Models.Roba", b =>
                {
                    b.HasOne("WebTemplate.Models.Vozilo", "Vozilo")
                        .WithMany("RobaUVozilu")
                        .HasForeignKey("VoziloID");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("WebTemplate.Models.Vozilo", b =>
                {
                    b.HasOne("WebTemplate.Models.Kompanija", "KompanijinoVozilo")
                        .WithMany("VozilaKompanije")
                        .HasForeignKey("KompanijinoVoziloID");

                    b.Navigation("KompanijinoVozilo");
                });

            modelBuilder.Entity("WebTemplate.Models.Kompanija", b =>
                {
                    b.Navigation("VozilaKompanije");
                });

            modelBuilder.Entity("WebTemplate.Models.Vozilo", b =>
                {
                    b.Navigation("RobaUVozilu");
                });
#pragma warning restore 612, 618
        }
    }
}
