// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20240309172136_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Distribucija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("BrojRadnika")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Distribucije");
                });

            modelBuilder.Entity("WebTemplate.Models.Podrucje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BrojBrojila")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumPotpisivanjaUgovora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistribucijaID")
                        .HasColumnType("int");

                    b.Property<long>("KorisnickiBroj")
                        .HasColumnType("bigint");

                    b.Property<int?>("PotrosacID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DistribucijaID");

                    b.HasIndex("PotrosacID");

                    b.ToTable("Podrucja");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("GodinaRodjenja")
                        .HasColumnType("bigint");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MestoRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Potrosaci");
                });

            modelBuilder.Entity("WebTemplate.Models.Podrucje", b =>
                {
                    b.HasOne("WebTemplate.Models.Distribucija", "Distribucija")
                        .WithMany("Podrucja")
                        .HasForeignKey("DistribucijaID");

                    b.HasOne("WebTemplate.Models.Potrosac", "Potrosac")
                        .WithMany("Podrucja")
                        .HasForeignKey("PotrosacID");

                    b.Navigation("Distribucija");

                    b.Navigation("Potrosac");
                });

            modelBuilder.Entity("WebTemplate.Models.Distribucija", b =>
                {
                    b.Navigation("Podrucja");
                });

            modelBuilder.Entity("WebTemplate.Models.Potrosac", b =>
                {
                    b.Navigation("Podrucja");
                });
#pragma warning restore 612, 618
        }
    }
}
