// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    partial class IspitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Ispit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("WebTemplate.Models.Rok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Rokovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Spoj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("IspitID")
                        .HasColumnType("int");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.Property<int?>("RokID")
                        .HasColumnType("int");

                    b.Property<int?>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IspitID");

                    b.HasIndex("RokID");

                    b.HasIndex("StudentID");

                    b.ToTable("Spojevi");
                });

            modelBuilder.Entity("WebTemplate.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Indeks")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("WebTemplate.Models.Spoj", b =>
                {
                    b.HasOne("WebTemplate.Models.Ispit", "Ispit")
                        .WithMany("StudentiPredmeti")
                        .HasForeignKey("IspitID");

                    b.HasOne("WebTemplate.Models.Rok", "Rok")
                        .WithMany("StudentiPredmeti")
                        .HasForeignKey("RokID");

                    b.HasOne("WebTemplate.Models.Student", "Student")
                        .WithMany("StudentPredmet")
                        .HasForeignKey("StudentID");

                    b.Navigation("Ispit");

                    b.Navigation("Rok");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WebTemplate.Models.Ispit", b =>
                {
                    b.Navigation("StudentiPredmeti");
                });

            modelBuilder.Entity("WebTemplate.Models.Rok", b =>
                {
                    b.Navigation("StudentiPredmeti");
                });

            modelBuilder.Entity("WebTemplate.Models.Student", b =>
                {
                    b.Navigation("StudentPredmet");
                });
#pragma warning restore 612, 618
        }
    }
}
