// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20240807160656_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Dimenzija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Sirina")
                        .HasColumnType("int");

                    b.Property<int>("Visina")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Dimenzije");
                });

            modelBuilder.Entity("WebTemplate.Models.Fotografija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrFotografija")
                        .HasColumnType("int");

                    b.Property<int?>("DimenzijaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PapirID")
                        .HasColumnType("int");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.Property<int?>("RamID")
                        .HasColumnType("int");

                    b.Property<string>("SlikaPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DimenzijaID");

                    b.HasIndex("PapirID");

                    b.HasIndex("ProdavnicaID");

                    b.HasIndex("RamID");

                    b.ToTable("Fotografije");
                });

            modelBuilder.Entity("WebTemplate.Models.Papir", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Papiri");
                });

            modelBuilder.Entity("WebTemplate.Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DnevnaZarada")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Prodavnice");
                });

            modelBuilder.Entity("WebTemplate.Models.Ram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BrRamova")
                        .HasColumnType("int");

                    b.Property<int?>("DimenzijaRamaID")
                        .HasColumnType("int");

                    b.Property<string>("Materijal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DimenzijaRamaID");

                    b.ToTable("Ramovi");
                });

            modelBuilder.Entity("WebTemplate.Models.Fotografija", b =>
                {
                    b.HasOne("WebTemplate.Models.Dimenzija", "Dimenzija")
                        .WithMany("DimenzijeFotografija")
                        .HasForeignKey("DimenzijaID");

                    b.HasOne("WebTemplate.Models.Papir", "Papir")
                        .WithMany("PapiriFotografija")
                        .HasForeignKey("PapirID");

                    b.HasOne("WebTemplate.Models.Prodavnica", "Prodavnica")
                        .WithMany("FotografijeUProdavnici")
                        .HasForeignKey("ProdavnicaID");

                    b.HasOne("WebTemplate.Models.Ram", "Ram")
                        .WithMany("FotografijeRamovi")
                        .HasForeignKey("RamID");

                    b.Navigation("Dimenzija");

                    b.Navigation("Papir");

                    b.Navigation("Prodavnica");

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("WebTemplate.Models.Ram", b =>
                {
                    b.HasOne("WebTemplate.Models.Dimenzija", "DimenzijaRama")
                        .WithMany("DimenzijeRamova")
                        .HasForeignKey("DimenzijaRamaID");

                    b.Navigation("DimenzijaRama");
                });

            modelBuilder.Entity("WebTemplate.Models.Dimenzija", b =>
                {
                    b.Navigation("DimenzijeFotografija");

                    b.Navigation("DimenzijeRamova");
                });

            modelBuilder.Entity("WebTemplate.Models.Papir", b =>
                {
                    b.Navigation("PapiriFotografija");
                });

            modelBuilder.Entity("WebTemplate.Models.Prodavnica", b =>
                {
                    b.Navigation("FotografijeUProdavnici");
                });

            modelBuilder.Entity("WebTemplate.Models.Ram", b =>
                {
                    b.Navigation("FotografijeRamovi");
                });
#pragma warning restore 612, 618
        }
    }
}
