// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20240810113123_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebtTemplate.Models.Automobil", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BojaID")
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumPoslednjeProdaje")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("MarkaID")
                        .HasColumnType("int");

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<string>("SlikaPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BojaID");

                    b.HasIndex("MarkaID");

                    b.HasIndex("ModelID");

                    b.ToTable("Automobili");
                });

            modelBuilder.Entity("WebtTemplate.Models.Boja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ModelID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ModelID");

                    b.ToTable("Boje");
                });

            modelBuilder.Entity("WebtTemplate.Models.Marka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Marke");
                });

            modelBuilder.Entity("WebtTemplate.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("MarkaID")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MarkaID");

                    b.ToTable("Modeli");
                });

            modelBuilder.Entity("WebtTemplate.Models.Automobil", b =>
                {
                    b.HasOne("WebtTemplate.Models.Boja", "Boja")
                        .WithMany("BojaAutomobila")
                        .HasForeignKey("BojaID");

                    b.HasOne("WebtTemplate.Models.Marka", "Marka")
                        .WithMany("MarkaAutomobila")
                        .HasForeignKey("MarkaID");

                    b.HasOne("WebtTemplate.Models.Model", "Model")
                        .WithMany("ModelAutomobila")
                        .HasForeignKey("ModelID");

                    b.Navigation("Boja");

                    b.Navigation("Marka");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("WebtTemplate.Models.Boja", b =>
                {
                    b.HasOne("WebtTemplate.Models.Model", "Model")
                        .WithMany("BojeModela")
                        .HasForeignKey("ModelID");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("WebtTemplate.Models.Model", b =>
                {
                    b.HasOne("WebtTemplate.Models.Marka", "Marka")
                        .WithMany("ModeliMarke")
                        .HasForeignKey("MarkaID");

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("WebtTemplate.Models.Boja", b =>
                {
                    b.Navigation("BojaAutomobila");
                });

            modelBuilder.Entity("WebtTemplate.Models.Marka", b =>
                {
                    b.Navigation("MarkaAutomobila");

                    b.Navigation("ModeliMarke");
                });

            modelBuilder.Entity("WebtTemplate.Models.Model", b =>
                {
                    b.Navigation("BojeModela");

                    b.Navigation("ModelAutomobila");
                });
#pragma warning restore 612, 618
        }
    }
}
